# Uncomment/comment the 'build:' and 'image' sections to build docker images locally or pull from
# dockerhub respectively


services:
  node:
#    image: electrumsvsdk/node:latest
    build:
      context: electrumsv_sdk
      dockerfile: electrumsv_sdk/builtin_components/node/Dockerfile
    ports:
      - "0.0.0.0:18332:18332"
    environment:
      - NODE_RPCALLOWIP=0.0.0.0/0
      - NODE_RPCBIND=0.0.0.0
      - NODE_PORT=18332

  electrumx:
#    image: electrumsvsdk/electrumx:latest
    build:
      context: electrumsv_sdk
      dockerfile: electrumsv_sdk/builtin_components/electrumx/Dockerfile
    ports:
      - "0.0.0.0:51001:51001"
    environment:
      - DAEMON_URL=http://rpcuser:rpcpassword@${DOCKER_GATEWAY_HOST:-host.docker.internal}:18332
    depends_on:
      - node

  electrumsv:
#    image: electrumsvsdk/electrumsv:latest
    build:
      context: electrumsv_sdk
      dockerfile: electrumsv_sdk/builtin_components/electrumsv/Dockerfile
    ports:
      - "0.0.0.0:9999:9999"
    environment:
      - RESTAPI_HOST=0.0.0.0
      - RESTAPI_PORT=9999
      - BITCOIN_NODE_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      - BITCOIN_NODE_PORT=18332
      - BITCOIN_NODE_RPCUSER=rpcuser
      - BITCOIN_NODE_RPCPASSWORD=rpcpassword
      - ELECTRUMX_CONNECTION_STRING=${DOCKER_GATEWAY_HOST:-host.docker.internal}:51001:t
    depends_on:
      - node
      - electrumx

  whatsonchain:
#    image: electrumsvsdk/whatsonchain:latest
    build:
      context: electrumsv_sdk/builtin_components/whatsonchain
      dockerfile: electrumsv_sdk/builtin_components/whatsonchain/Dockerfile
    ports:
      - "0.0.0.0:3002:3002"
    environment:
      - RPC_HOST=host.docker.internal
      - RPC_PORT=18332
      - RPC_USERNAME=rpcuser
      - RPC_PASSWORD=rpcpassword
      - ELECTRUMX_HOST=host.docker.internal
      - ELECTRUMX_PORT=51001
    depends_on:
      - node

  whatsonchain_api:
    #    image: electrumsvsdk/whatsonchain:latest
    build:
      context: electrumsv_sdk/builtin_components/whatsonchain_api
      dockerfile: electrumsv_sdk/builtin_components/whatsonchain_api/Dockerfile
    ports:
      - "0.0.0.0:12121:12121"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=12121
      - BITCOIN_NODE_HOST=host.docker.internal
      - BITCOIN_NODE_PORT=18332
    depends_on:
      - node

  merchant_api:
    #    image: electrumsvsdk/merchant_api:latest
    build:
      context: electrumsv_sdk/builtin_components/merchant_api
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:45111:45111"
      - "0.0.0.0:28332:28332"
    environment:
      - NODE_HOST=host.docker.internal
      - NODE_RPC_PORT=18332
      - NODE_RPC_USERNAME=rpcuser
      - NODE_RPC_PASSWORD=rpcpassword
      - NODE_ZMQ_PORT=28332
      - MERCHANT_API_HOST=0.0.0.0
      - MERCHANT_API_PORT=45111
    depends_on:
      - node
