STATUS_MONITOR_API = "http://127.0.0.1:5000/api/status"

DEFAULT_ID_ELECTRUMSV = "electrumsv1"
DEFAULT_ID_ELECTRUMX = "electrumx1"
DEFAULT_ID_NODE = "node1"
DEFAULT_ID_STATUS = "status1"
DEFAULT_ID_INDEXER = "indexer1"

DEFAULT_PORT_ELECTRUMSV = 9999
