trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    - features/*
  paths:
    exclude: [ 'README.md' ]

jobs:
- job: linux
  pool: {vmImage: 'ubuntu-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        export "CIBW_BUILD=cp37-* cp38-*"
        export CIBW_BUILD_VERBOSITY=1
        export CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.5.5
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'

- job: macos
  pool: {vmImage: 'macOS-10.15'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        export "CIBW_BUILD=cp37-* cp38-*"
        export CIBW_BUILD_VERBOSITY=1
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.5.5
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'

- job: windows
  pool: {vmImage: 'windows-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set "CIBW_BUILD=cp37-* cp38-*"
        set CIBW_BUILD_VERBOSITY=1
        python3 -m pip install --upgrade pip
        pip install cibuildwheel==1.5.5
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'
